export default {
  metros: [
    {
      line: "1",
      slug: "normal_trav",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "2",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "3",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "3B",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "4",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "5",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "6",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "7",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "7B",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "8",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "9",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "10",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "11",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "12",
      slug: "alerte",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "13",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "14",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
  ],
  rers: [
    {
      line: "A",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "B",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "C",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "D",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "E",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
  ],
  tramways: [
    {
      line: "1",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "2",
      slug: "normal_trav",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "3A",
      slug: "alerte",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "3B",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "4",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "5",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "6",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "7",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
    {
      line: "8",
      slug: "normal",
      title: "Trafic normal",
      message: "Trafic normal sur l'ensemble de la ligne.",
    },
  ],
};
